# Assignment  3:


Question 6:

In [1]:
import numpy as np

arr=np.arange(1,13).reshape(3,4)
print(arr)
print()

print(np.unique(arr,return_counts=True))

print()
#----------------------------------------------------------------------------------------
arr=np.array([[24,12,99,2],[65,75,99,20],[36,12,91,82],[73,12,65,24]])
print(arr)
print()

print(np.unique(arr,return_counts=True))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

[[24 12 99  2]
 [65 75 99 20]
 [36 12 91 82]
 [73 12 65 24]]

(array([ 2, 12, 20, 24, 36, 65, 73, 75, 82, 91, 99]), array([1, 3, 1, 2, 1, 2, 1, 1, 1, 1, 2], dtype=int64))
