# Assignment  3:


QuestionA 5:

In [1]:
import numpy as np

arr=np.arange(1,13)
print(arr)
print()

arr=arr.reshape(3,4)
print(arr)
print() 
print(np.vstack(arr))
print()
print(np.hstack(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
