# Assignment  3:


Question 3:

In [1]:
import numpy as np

arr = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print(arr)
print("No of rows : ",np.size(arr,0))
print("No of Columns : ",np.size(arr,1))
print()
print("Shape of array: ",np.shape(arr))
print("Dimention of array : ",np.ndim(arr))

[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
No of rows :  3
No of Columns :  4

Shape of array:  (3, 4)
Dimention of array :  2
