# Assignment  3:


QuestionA 4:

In [1]:
import numpy as np

arr=np.arange(1,13)
print(arr)
print()

arr=arr.reshape(3,4)
print(arr)
print()

print(arr[:,np.newaxis])
print(arr[np.newaxis].shape)

print(np.expand_dims(arr, 0))
print(np.expand_dims(arr, 0).shape)

print(np.expand_dims(arr, 1))
print(np.expand_dims(arr, 1).shape)

print(np.expand_dims(arr, 2))
print(np.expand_dims(arr, 2).shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
(1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
(3, 1, 4)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
(3, 4, 1)
